name: build
on:
  #push
  workflow_dispatch:
jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
          with: COMMIT_TIME=$(git show -s --format=%ci dd28288f)
     # - name: Test with input
      #  uses: actions/hello-world-docker-action@master
      #  with:
      #    who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}
  currenttime:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+08:00"
    - name: Use current time
      env:
        TIME: "${{ steps.current-time.outputs.time }}"
        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        YEAR: "${{ steps.current-time.outputs.year }}"
        DAY: "${{ steps.current-time.outputs.day }}"
      run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
