name: merging request

on:
 # push:
  pull_request:
    types: [review_requested]
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: ${{ github.event.requested_team.name == 'madhu-us' }}
    steps:
      - run: echo 'A review from madhu-us was requested'
