name: deploy 
on: [push] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Set current date as env variable 
        run: echo "NOW=$(date +'%Y-%m-%d T%H:%M:%S')" >> $GITHUB_ENV 
      - name: Echo current date 
        run: echo $NOW # Gives "2022-12-11T01:42:
