name: deploy 
on: [push] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
        name: Set current date as env variable 
      - run: |
          echo "NOW=$(date +'D:%Y-%m-%d T:%H:%M:%S')" >> $GITHUB_ENV
          echo $NOW
      #- name: Echo current date 
      #  run: echo $NOW # Gives "2022-12-11T01:42:
        # echo "$NOW"
